//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace highchart_line.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointementModels
    {
        public int AppointmentID { get; set; }
        public int idDoctors { get; set; }
        public System.DateTime DtEdit { get; set; }
        public System.DateTime dateTime { get; set; }
        public int idPatients { get; set; }
    
        public virtual MedecinConventionnes MedecinConventionnes { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
