//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace highchart_line.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultationDetails
    {
        public int ConsultDetailID { get; set; }
        public int ConsultationID { get; set; }
        public string Comment { get; set; }
        public string CNAM { get; set; }
    
        public virtual Consultations Consultations { get; set; }
    }
}
