//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace highchart_line.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultations()
        {
            this.ConsultationDetails = new HashSet<ConsultationDetails>();
            this.Orders = new HashSet<Orders>();
            this.RDVs = new HashSet<RDVs>();
        }
    
        public int ConsultationID { get; set; }
        public string diagnostic { get; set; }
        public string UserID { get; set; }
        public string Username { get; set; }
        public int idPatients { get; set; }
        public string natureVisite { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ConduiteTenir { get; set; }
        public string CNAM { get; set; }
        public bool PrescMed { get; set; }
        public bool ExplorRadio { get; set; }
        public string ExplorRadioComment { get; set; }
        public bool ExplorBio { get; set; }
        public string ExplorBioComment { get; set; }
        public bool Transfert { get; set; }
        public string TransfertComment { get; set; }
        public bool Hospitalisation { get; set; }
        public string HospitalComment { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultationDetails> ConsultationDetails { get; set; }
        public virtual Patients Patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDVs> RDVs { get; set; }
    }
}
