//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace highchart_line.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileDetails
    {
        public System.Guid Id { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public int IdPatients { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
