//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace highchart_line.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedecinConventionnes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedecinConventionnes()
        {
            this.AppointementModels = new HashSet<AppointementModels>();
            this.Events = new HashSet<Events>();
        }
    
        public int idDoctors { get; set; }
        public string nameDoctors { get; set; }
        public string emailDoctors { get; set; }
        public string phoneDoctors { get; set; }
        public string JourTravail1 { get; set; }
        public System.DateTime TimeTravail1 { get; set; }
        public string JourTravail2 { get; set; }
        public System.DateTime TimeTravail2 { get; set; }
        public int idSpecialite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointementModels> AppointementModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Events> Events { get; set; }
        public virtual Specialites Specialites { get; set; }
    }
}
