//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace highchart_line.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patients()
        {
            this.AppointementModels = new HashSet<AppointementModels>();
            this.Consultations = new HashSet<Consultations>();
            this.FileDetails = new HashSet<FileDetails>();
        }
    
        public int IdPatients { get; set; }
        public string MatriculePatients { get; set; }
        public string NomPatient { get; set; }
        public string PrenomPatient { get; set; }
        public string Gender { get; set; }
        public string PhonePatients { get; set; }
        public System.DateTime DOB { get; set; }
        public string Parente { get; set; }
        public string MaladieChronique { get; set; }
        public string APCI { get; set; }
        public string CodeAPCI { get; set; }
        public int IdUsine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointementModels> AppointementModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultations> Consultations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileDetails> FileDetails { get; set; }
        public virtual Usines Usines { get; set; }
    }
}
